# Generated by Django 5.0.1 on 2024-01-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha_desde',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha_hasta',
            new_name='fecha_ini',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='localidad_desde',
            new_name='localidad_fin',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='localidad_hasta',
            new_name='localidad_ini',
        ),
    ]
