# Generated by Django 5.0.1 on 2024-01-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_rename_fecha_desde_viaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='perfil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitacora.perfil', verbose_name='Usuario'),
        ),
    ]
