# Generated by Django 5.0.1 on 2024-01-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_perfil_user_alter_perfil_pais_origen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
