# Generated by Django 5.0.1 on 2024-02-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0007_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='localidad_fin',
            field=models.CharField(max_length=100, verbose_name='Localidad Destino   '),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='localidad_ini',
            field=models.CharField(max_length=100, verbose_name='Localidad de Inicio '),
        ),
        migrations.CreateModel(
            name='Viaje_Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(blank=True, choices=[('Ida', 'Ida'), ('Vuelta', 'Vuelta')], max_length=50, verbose_name='Sentido de la Etapa ')),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('localidad_ini', models.CharField(max_length=100, verbose_name='Localidad de Inicio ')),
                ('localidad_fin', models.CharField(max_length=100, verbose_name='Localidad de Fin   ')),
                ('km_recorridos', models.FloatField()),
                ('comentarios', models.CharField(max_length=500)),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitacora.viaje')),
            ],
        ),
    ]
